version: '3.9'

services:
  api1:
    build: .
    environment:
      - DATABASE_URL=postgresql://student_user:student_pass@db:5432/student_db
    depends_on:
      - db
    expose:
      - "5000"

  api2:
    build: .
    environment:
      - DATABASE_URL=postgresql://student_user:student_pass@db:5432/student_db
    depends_on:
      - db
    expose:
      - "5000"

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: student_user
      POSTGRES_PASSWORD: student_pass
      POSTGRES_DB: student_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:80"
    depends_on:
      - api1
      - api2

volumes:
  postgres_data:
