version: '3.9'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: studentdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - db_data:/var/lib/postgresql/data

  api1:
    build: .
    environment:
      DATABASE_URL: postgres://user:password@db:5432/studentdb
    depends_on:
      - db

  api2:
    build: .
    environment:
      DATABASE_URL: postgres://user:password@db:5432/studentdb
    depends_on:
      - db

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api1
      - api2

volumes:
  db_data:
