name: Student API CI/CD Pipeline

on:
  push:
    paths:
      - "app/**"
      - "Dockerfile"
      - "requirements.txt"
      - "Makefile"
      
  workflow_dispatch: # Allow manual trigger

jobs:
  build-api:
    runs-on: self-hosted # Uses a self-hosted GitHub runner
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install Dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

  run-tests:
    runs-on: self-hosted
    needs: build-api
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install Dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Tests
        run: |
          source venv/bin/activate
          make test

  lint-code:
    runs-on: self-hosted
    needs: build-api
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install Dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Code Linting
        run: |
          source venv/bin/activate
          make lint

  docker-login:
    runs-on: self-hosted
    needs: [run-tests, lint-code]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

  docker-build-push:
    runs-on: self-hosted
    needs: docker-login
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Create & Activate Virtual Environment
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      # Debug Docker Info
      - name: Debug Docker Info
        run: |
          docker --version
          docker info

      # Debug Docker Login
      - name: Debug Docker Login
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker info

      # Debug Docker Build
      - name: Debug Docker Build
        run: |
          docker build -t mydockerhubuser/mydockerhubrepo:1.0.0 .
          docker images

      # Debug Docker Push
      - name: Debug Docker Push
        run: |
          docker push mydockerhubuser/mydockerhubrepo:1.0.0 || docker logout
